# Generated by Django 5.2.15 on 2026-06-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('translating', 'Translating'), ('rebuilding', 'Rebuilding'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=150)),
                ('source_lang', models.CharField(max_length=100)),
                ('target_lang', models.CharField(max_length=100)),
                ('total_pages', models.IntegerField(default=0)),
                ('processed_pages', models.IntegerField(default=0)),
                ('failed_chunks', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(default=0)),
                ('page_start', models.IntegerField(default=1)),
                ('page_end', models.IntegerField()),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_progress'), ('done', 'Done'), ('failed', 'Failed')], max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('layout_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.translationjob')),
            ],
        ),
    ]
