# Generated by Django 5.2.15 on 2026-06-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
