# Generated by Django 5.2.15 on 2026-06-12 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('jobs', '0002_translationjob_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='input_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
