# Generated by Django 6.0.6 on 2026-06-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_translationjob_input_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationjob',
            old_name='input_field',
            new_name='input_file',
        ),
    ]
