# Generated by Django 6.0.6 on 2026-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_input_field_translationjob_input_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='output_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
