# Generated by Django 5.2.15 on 2026-06-06 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_format', models.CharField(choices=[('pdf', 'Pdf'), ('docx', 'Docx'), ('pptx', 'Pptx'), ('txt', 'Txt')], max_length=100)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField()),
                ('is_scanned_pdf', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
